# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 62a644d1dd7ab11a5aa884bb24910dbf2dc193e392eef34b0bf61b7e589efd6c2057ef5c7fef110c66adfc75f015accf2354b47463545a6422953a14d30f3c5a

test:
  secret_key_base: 4cf5e8adc11a7e5a3ae775e1621860ac18c355ae7a940cec0e96bc3c9a6b9000b5dbceb11f8e8a6d3beeb001e932a69e72ae9384e85cfa9186873470df2a7935

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
